### ISSUE TITLE
Requested features

### ISSUE THREAD

**Issue by chinatsu-chan** [nzcv/4ind#1]
I would add a --copy for copying to clipoard

Output should include the related reply paragraph id (e.g. http://boards.4chan.org/g/thread/50332413#p50334652) instead of just http://boards.4chan.org/g/thread/50332413.

Should check for archived posts by default (why doesn't it?) if all you have is the URL you don't know that a thread is archived. So instead the program should try the normal way and then search for archived if that doesn't work.

**Comment by chinatsu-chan** [comment]
Also forgot 2 mention support for thumbs

**Comment by nzcv** [comment]
@chinatsu-chan 
>Should check for archived posts by default (why doesn't it?) if all you have is the URL you don't know that a thread is archived. So instead the program should try the normal way and then search for archived if that doesn't work.

Some boards have 3k+ archived threads, crawling through all of them by default would be unreasonable. Just use the --archived flag.

**Comment by chinatsu-chan** [comment]
Sounds good
